Midterm/DeliveryProject/Models/DeliveryMarket.cs
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using DataLibrary.Models;
using DataLibrary;

namespace DeliveryProject.Models { 
    public class DeliveryMarket {
 
        public List<Order> GetOrder(){
            var getList = new Prog();
            var list = getList.ReadOrder();
            return list;
        }

        public List<Road> GetRoad(){
            var getList = new Prog();
            var list = getList.ReadRoad();
            return list;
        }
        
        public List<Category> GetCategory(){
            var getList = new Prog();
            var list = getList.ReadCategory();
            return list;
        }

        public List<Record> GetRecord(){
            var getList = new Prog();
            var roadList = getList.ReadRoad();
            var orderList = getList.ReadOrder();
            var caregoryList = getList.ReadCategory();

            var model = new List<Record>();

            var order = roadList  
                                .Join(orderList,
                                    road => road.Id,
                                    order => order.MarketId,
                                    (market, product) => new 
                                    {
                                        market,
                                        product
                                    })
                                .ToList();
            var join = marketList  
                    .Join(productList,
                        markets => markets.Id,
                        products => products.MarketId,
                        (markets, products) => new 
                        {
                            markets,
                            products
                        })
                    .ToList();           
            var newJoin = join
                    .Where(x => x.markets.Name.Equals(value))
                    .Select( x => 
                    new {
                        name = x.products.Name, 
                        price = x.products.Price,
                        amount = x.products.Amount
                    }).ToList();


            var sortPrice = marketProduct
                            .Where(x => x.market.Name.Equals(value))
                            .Sum(x=>x.product.Price);

            foreach (var item in newJoin)  {     
            model.Add(new Sum { 
                    name = item.name, 
                    price = (item.price).ToString(), 
                });
            }
          
            model.Add(new Sum {
                    sum = sortPrice.ToString()  
                });
            return model;
        }
    }
}

Midterm/DeliveryProject/Models/ErrorViewModel.cs
using System;

namespace Midterm.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Midterm/DeliveryProject/Models/Records.cs
using System.Collections.Generic;
using System;

namespace DataLibrary.Models 
{
    public class Records
    {
        public string Customer {get;set;}
        public string DestinationOne {get; set;}
        public string DestinationTwo {get; set;}
        public string Type {get; set;}   
        public DateTime OrderedDate {get; set;} 

    }
}

Midterm/DeliveryProject/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Midterm.Models;
using DataLibrary.Models;
using DataLibrary;
using DeliveryProject.Models;

namespace DeliveryProject.Controllers
{
    public class DeliveryController : Controller
    {
        private DeliveryMarket dc;
        
        public DeliveryController()
        {
           dc = new DeliveryMarket();
        }
    
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Order()
        {
            var orders = dc.GetOrder();
            return View(orders);
        }

        public IActionResult Road()
        {
            var records = dc.GetRoad();
            ViewData["Message"] = "Your contact page.";

            return View(records);
        }

        public IActionResult Category()
        {
            var categories = dc.GetCategory();
            ViewData["Message"] = "Your contact page.";

            return View(categories);
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Midterm/DeliveryProject/Views/Delivery/Category.cshtml
@using System.Linq
@using DataLibrary.Models

@model List<Category>
@using System.Collections.Generic
<table class="table">
    <thead>
     <tr>
       <th> ID  </th>
       <th> Type  </th>
       <th>Weight</th>
        <th>Price</th>
        <th>Category</th>
     </tr>
    </thead>
    <tbody>
    @foreach(var item in Model)
    {
        <tr>
            <td> @item.ID </td>
            <td> @item.Type </td>
            <td>@item.Weight</td>
            <td>@item.Price</td>
            <td>@item.Level</td>
        </tr>
    }
    </tbody>
</table> 

Midterm/DeliveryProject/Views/Delivery/Order.cshtml
@using System.Linq
@using DataLibrary.Models

@model List<Order>
@using System.Collections.Generic
<table class="table">
    <thead>
     <tr>
        <th> Dest1  </th>
        <th> Dest2  </th>
        <th>Type</th>
        <th>Ordered Date</th>
        <th>Customer</th>
     </tr>
    </thead>
    <tbody>
    @foreach(var item in Model)
    {
        <tr>
            <td> @item.DestinationOne </td>
            <td> @item.DestinationTwo </td>
            <td>@item.Type</td>
            <td>@item.OrderedDate</td>
            <td>@item.Customer</td>
        </tr>
    }
    </tbody>
</table> 

Midterm/DeliveryProject/Views/Delivery/Records.cshtml
@using System.Linq
@using DataLibrary.Models

@model List<Records>
@using System.Collections.Generic
<table class="table">
    <thead>
     <tr>
        <th>Customer  </th>
        <th> From  </th>
        <th>To</th>
        <th>Object</th>
        <th>OrderedDate</th>
        <th>DeliveredDate</th>
     </tr>
    </thead>
    <tbody>
    @foreach(var item in Model)
    {
        <tr>
            <td> @item.Customer </td>
            <td> @item.DestinationOne </td>
            <td>@item.DestinationTwo</td>
            <td>@item.Type</td>
            <td>@item.OrderedDate</td>
            <td>@item.DeliveredDate</td>
            <td>@item.Level</td>
             <td>@item.Price</td>

            
            
        </tr>
    }
    </tbody>
</table> 

Midterm/DeliveryProject/Views/Delivery/Road.cshtml
@using System.Linq
@using DataLibrary.Models

@model List<Road>
@using System.Collections.Generic
<table class="table">
    <thead>
     <tr>
        <th> Dest1  </th>
        <th> Dest2  </th>
        <th> Duration  </th>
     </tr>
    </thead>
    <tbody>
    @foreach(var item in Model)
    {
        <tr>
            <td> @item.DestOne </td>
            <td> @item.DestOne </td>
            <td> @item.Duration </td>
        </tr>
    }
    </tbody>
</table> 

Midterm/DeliveryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Midterm</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Midterm</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Delivery" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Delivery" asp-action="Order">Order</a></li>
                    <li><a asp-area="" asp-controller="Delivery" asp-action="Road">Info</a></li>
                    <li><a asp-area="" asp-controller="Delivery" asp-action="Category">Category</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Midterm</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>